# Generated by Django 3.2.15 on 2022-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
