# Generated by Django 3.2.15 on 2022-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsApp', '0002_auto_20220820_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, default='2020-03-13'),
        ),
    ]
